name: Python SDK CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
  pull_request:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            '3.10'
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: make env

      - name: Clean
        run: make clean

#      - name: Lint
#        run: make lint

      - name: Build
        run: make build

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    name: Test - Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            "2.7",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "pypy-2.7",
            "pypy-3.7",
            "pypy-3.8",
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: make env

      - name: Clean
        run: make clean

      - name: Test
        run: make test

  code-coverage:
    needs: [ test ]
    runs-on: ubuntu-latest
    name: Report code coverage - Python ${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            '3.10'
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: make env

      - name: Clean
        run: make clean

      - name: Test
        run: make test

      - uses: AndreMiras/coveralls-python-action@develop
